name: CI/CD for TodoApp

on:
  push:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Trigger Render Deployment
      run: |
        curl -X POST "https://api.render.com/deploy/srv-${{ secrets.SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"
