name: CI/CD for TodoApp

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "TEST_DATABASE_URL=sqlite:///./test.db" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Set up environment variables
        run: |
          echo "RENDER_API_KEY=${{ secrets.RENDER_API_KEY }}" >> $GITHUB_ENV
          echo "SERVICE_ID=${{ secrets.SERVICE_ID }}" >> $GITHUB_ENV

      - name: Trigger Render Deployment
        run: |
          RESPONSE=$(curl -X POST "https://api.render.com/deploy/srv-${{ secrets.SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}")
          echo "Render API response: $RESPONSE"
          if [[ "$RESPONSE" != *"success"* ]]; then
            echo "Render deployment failed!"
            exit 1
          fi
